### ISSUE TITLE
no-exclusive-tests: additionalTestFunctions should support methods

### ISSUE THREAD

**Issue by vitalets** [lo1tuma/eslint-plugin-mocha#102]
I'm using this plugin with selenium-webdriver tests that uses wrapped mocha functions as methods of `test` object:

``` js
test.describe('Google Search', function() {
  var driver;

  test.before(function() {
    driver = new webdriver.Builder()
        .forBrowser('firefox')
        .build();
  });

  test.it('should append query to title', function() {
    driver.get('http://www.google.com');
    driver.findElement(By.name('q')).sendKeys('webdriver');
    driver.findElement(By.name('btnG')).click();
    driver.wait(until.titleIs('webdriver - Google Search'), 1000);
  });

  test.after(function() {
    driver.quit();
  });
});
```

Full example from selenium repo: https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/example/google_search_test.js

Setting `additionalTestFunctions` does not work:

```
  "settings": {
    "mocha/additionalTestFunctions": [
      "test.describe",
      "test.it"
    ]
  }
```

Is it possible to support this?
Thanks!

**Comment by lo1tuma** [comment]
Sounds like a useful addition. The question is should we implement a generic solution which also supports `foo.bar.baz.it`?

**Comment by vitalets** [comment]
> Sounds like a useful addition. The question is should we implement a generic solution which also supports foo.bar.baz.it?

maybe add option which checks that mocha's `describe / it` are methods of some object as well as separate functions? i s it possible in eslint?
It will support `foo.bar.baz.it` (although I've never heard about such calls):
```
"settings": {
    "mocha/checkMethods": true
}

**Comment by vitalets** [comment]
Hi @lo1tuma any news on it? It would be nice to have this..

**Comment by jfmengels** [comment]
I know it's not the same exactly, but in the meantime you could use http://eslint.org/docs/rules/no-restricted-properties to forbid the use of these.
Or for the implementer, this could be a source of inspiration for how to implement this rule.

**Comment by vitalets** [comment]
Great thanks! 👍
