### ISSUE TITLE
Rule proposal: no-nested-its

### ISSUE THREAD

**Issue by ahuff44** [lo1tuma/eslint-plugin-mocha#108]
Today I accidentally wrote some tests like this:

```
describe("a", function() {
  it("b", function() {
    it("c1", function() {
       expect(...);
    });

    it("c2", function() {
       expect(...);
    });
  });
});
```

instead of like this:

```
describe("a", function() {
  describe("b", function() { // <-----------
    it("c1", function() {
       expect(...);
    });

    it("c2", function() {
       expect(...);
    });
  });
});
```

This caused mocha to not run tests "c1" or "c2" at all, since they were accidentally declared inside an `it` block instead of a `describe` block.

I only noticed because my code coverage tool said it was missing certain execution branches that I could have sworn I had written tests for. A linter setting to point out this subtle mistake would be helpful IMO.

**Comment by lo1tuma** [comment]
👍  I’ve also seen this mistake a few times, that’s why I already implemented such a rule for our internal use at work, but I guess I could publish this rule in the next couple of days 😉 .

**Comment by jfmengels** [comment]
Sounds useful to me!
