### ISSUE TITLE
add a preset with all rules enabled

### ISSUE THREAD

**Issue by graingert** [lo1tuma/eslint-plugin-mocha#116]

**Comment by graingert** [comment]
I've created https://www.npmjs.com/package/eslint-config-plugin-mocha

**Comment by lo1tuma** [comment]
Thanks for the issue. Can you explain what a use-case would be for such a preset? Some rules don't do anything without further configuration when they are enabled, `valid-suite-description` for example.

**Comment by graingert** [comment]
@lo1tuma ah I didn't notice that one. It's probably not worth including that.

The usecase is that I prefer to disable a few rules rather than enable most of them.

**Comment by lo1tuma** [comment]
That would mean adding new rules would be always a breaking change. 
I am not sure if such a preset would provide enough value, especially as this plugin doesn't have a lot of rules.

**Comment by graingert** [comment]
@lo1tuma it would only be a breaking change in the preset.

**Comment by lo1tuma** [comment]
Yes, but that would be part of this package wouldn't it? Similar as the recommended config we already provide.

**Comment by graingert** [comment]
@lo1tuma it would be a separate package.

**Comment by lo1tuma** [comment]
Ah ok, so then I don't really understand the purpose of this issue. You already created a separate package for that.

**Comment by graingert** [comment]
@lo1tuma I was hoping to hand it over to you

**Comment by lo1tuma** [comment]
Sorry, but as I don’t have any need for such a preset personally I don’t want to take over maintenance of this package.

**Comment by graingert** [comment]
k
