### ISSUE TITLE
Release 4.8.0?

### ISSUE THREAD

**Issue by jfmengels** [lo1tuma/eslint-plugin-mocha#117]
4.7.0 has been out for a while, and contains nice things like autofix for no-mocha-arrows. I thought we could release 4.8.0 now.

I can (probably) do it myself, but I was wandering whether there was something missing before releasing.

**Comment by jfmengels** [comment]
Actually, never mind, I found some errors in the fixer. Will submit a PR first, and we can release afterwards.

**Comment by lo1tuma** [comment]
@jfmengels Yeah, I totally forgot about doing a release, thanks for reminding. Maybe we can even get #114 in.
Also please feel free to make a release whenever you think it makes sense, I totally trust you in that regard 😉 .

**Comment by lo1tuma** [comment]
I’ve just released the new version. 🎅  🎄 🎁

**Comment by jfmengels** [comment]
Awesome, thanks! :)
