### ISSUE TITLE
is there a way to turn off auto fixing with --fix for no-skipped-tests

### ISSUE THREAD

**Issue by anilnamde** [lo1tuma/eslint-plugin-mocha#124]
While trying auto fix we realised that mocha is converting all "xit", "it.skip" ... into "it" which is adding the test into scope. Ideal case for us would be if it just raises warning or shows error.

Is there any way we can turn off the autofix for specific rule ?

**Comment by lo1tuma** [comment]
AFAIK that’s not possible in eslint right now. Applying fixes is acutall part of eslint core, the rule just reports that it has a possible fix for the problem found, but it doesn’t apply the fix, that is done by eslint when you provide the `--fix` CLI option.

It might be possible to skip fixes for certein rule if you use eslint programmatically. If that is not an option I would suggest to create a feature request at eslint.

**Comment by lo1tuma** [comment]
There is already a discusion about this topic, see: https://github.com/eslint/eslint/issues/8018.

**Comment by anilnamde** [comment]
right thanks @lo1tuma
