### ISSUE TITLE
problem overriding parent rule

### ISSUE THREAD

**Issue by cuongluu8** [lo1tuma/eslint-plugin-mocha#129]
I have a root .eslint file that contains the rule `"prefer-arrow-callback": "error"`.
Within my `test` subfolder, I have a `.eslint` file that has just
```
{
    "env": {
        "mocha": true
    },
    "plugins": [
        "mocha"
    ],
    "rules": {
        "mocha/no-exclusive-tests": "error"
    }
}
```
However eslint still throws errors for `prefer-arrow-callback`.  Won't the mocha plugin override this rule by default?

**Comment by lo1tuma** [comment]
No the plugin doesn’t override any configs. The config of your subfolder inherits the config from the parent folder, see [the official eslint documentation about config files](http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy).
