### ISSUE TITLE
valid-suite/test-description rules don't handle template literals

### ISSUE THREAD

**Issue by shusak** [lo1tuma/eslint-plugin-mocha#139]
When the descriptions are a template literal, they are not processed by these rules. 

The rules need to look to see if the argument is a TemplateLiteral and navigate to it's raw or cooked value to run the regEx on.

**Comment by hinhengchan** [comment]
+1, having the same issue for both rules `valid-suite-description` and `valid-test-description`

**Comment by lo1tuma** [comment]
I think we could only check template literals without any expressions or tags.
