### ISSUE TITLE
Rule proposal: no only

### ISSUE THREAD

**Issue by karishnu** [lo1tuma/eslint-plugin-mocha#191]
We often forget to remove the 'only' after 'describe' or 'it' while pushing the code. If there was a rule that did not allow an 'only', our pipeline should detect an error which would make us fix it.

**Comment by lo1tuma** [comment]
Hi @karishnu, such a rule already exist, have a look at [`no-exclusive-tests`](https://github.com/lo1tuma/eslint-plugin-mocha/blob/d36c1499133ab688bd81a650e19f0d0cd11ea248/docs/rules/no-exclusive-tests.md)
