### ISSUE TITLE
Rule proposal: no-after-hooks

### ISSUE THREAD

**Issue by Lakitna** [lo1tuma/eslint-plugin-mocha#194]
Cypress (which uses Mocha) has a great writeup about why you should not use `after` and `afterEach`. It would be nice to have that in lint rule form.

https://docs.cypress.io/guides/references/best-practices.html#Using-after-or-afterEach-hooks

**Comment by lo1tuma** [comment]
Seems like this anti pattern is very specific to cypress. I think if one uses hooks, `after` and `afterEach` still makes sense, especially for cleaning up allocated resources. For example when tests are creating files the you probably don’t want them lying around until you run the test suite the next time.

Maybe we can extend the existing rule `no-hooks` to accept an optional parameter which lets you specify which hooks are forbidden.

**Comment by Lakitna** [comment]
I think it's very dependent on your test setup, but I've personally never had to use `after` or `afterEach`. I also thought about adding it behind an option in `no-hooks` but the name `no-hooks` does not imply you can disallow only certain hooks. On the other hand, adding it as a new rule probably introduces duplication.

**Comment by lo1tuma** [comment]
Actually this has been already proposed in #110.

**Comment by Lakitna** [comment]
Whoops. I looked but didn't find that one.
