### ISSUE TITLE
no-setup-in-describe: disallows `this.timeout()`/`this.slow()`

### ISSUE THREAD

**Issue by straub** [lo1tuma/eslint-plugin-mocha#208]
As the title says. Is this intentional? I don't see any mention of it in the docs.

If this is considered a bug, I'd be happy to try my hand at a PR to fix!

Thanks for your time :)

**Comment by lo1tuma** [comment]
Great catch. I would consider that as a bug. Any other opinions: @donabrams, @Lakitna?

**Comment by straub** [comment]
In the absence of other opinions, I suppose a PR would be welcome? I take take a pass at this :)
