### ISSUE TITLE
Performance: plugin adds 150-200ms to ESLint startup time because of ramda

### ISSUE THREAD

**Issue by victor-homyakov** [lo1tuma/eslint-plugin-mocha#213]
ESLint is frequently used in pre-commit hooks. Just adding `eslint-mocha-plugin` makes linting and commiting noticeably slower even when there is nothing to lint.

**Steps to reproduce**

1. Create clean new folder
2. Install `npm i eslint-mocha-plugin`
3. Create script and execute it in Node.js:
  ```js
const label = 'require plugin';
console.time(label);
const plugin = require('eslint-plugin-mocha');
console.timeEnd(label);
  ```

On MacBook Pro with 2,7 GHz Intel Core i5 it gives me 150-200 ms. In other words, just adding this plugin slows startup of ESLint by 150-200ms.

The problem is in `require('ramda')` - loading ramda module requires that much time. It's OK for long-running applications, but for command-line utilities it is inappropriately slow.

Is it possible to speedup startup time of plugin by rewriting the code without ramda?

**Comment by lo1tuma** [comment]
What makes you think this is caused by ramda? On my machine it takes ~170ms for requiring `eslint-plugin-mocha`, but only ~70ms for requiring `ramda`.

**Comment by lo1tuma** [comment]
I’ve made some optimizations in #214. I think it is not related to the CPU speed, but rather to I/O speed. The ramda entrypoint file does ~250 `require` calls.

**Comment by victor-homyakov** [comment]
> What makes you think this is caused by ramda?

1. I profiled requiring `index.js` - most of the time was spent on `require('./lib/rules/no-exclusive-tests')`
2. Most of the time in `no-exclusive-tests.js` was spent on `const astUtils = require('../util/ast');`
3. Profiling ast utils pointed me to line `const R = require('ramda');`
