### ISSUE TITLE
Modularise core

### ISSUE THREAD

**Issue by tlvince** [lo1tuma/eslint-plugin-mocha#24]
I maintain [eslint-plugin-jasmine](https://github.com/tlvince/eslint-plugin-jasmine) and noticed some crossover between eslint-plugin-mocha and eslint-plugin-jasmine.

Jasmine and Mocha share the same general `describe`/`it` syntax and in cases where they differ, for example in [exclusive](https://github.com/lo1tuma/eslint-plugin-mocha/blob/11d85783849e03c94c006f458db9f22e077c6229/lib/rules/no-exclusive-tests.js) (Mocha) or [focused](https://github.com/tlvince/eslint-plugin-jasmine/blob/def87477edbb6182547e26e7dd871c53fa8ca84c/lib/rules/no-focused-tests.js) (Jasmine) tests, similar if not the same basic matchers apply.

Perhaps we could extract "core" functionality where it makes sense, a la [standard](https://github.com/feross/standard/issues/87)/semistandard?

**Comment by lo1tuma** [comment]
Hi, I really like the idea of working together and avoid duplicating implementation details across different plugins.

Do you already have a clear vision on what could be extracted?

@lxanders Do you have any objections?

BTW: I really like the [`no-suite-dupes`](https://github.com/tlvince/eslint-plugin-jasmine/blob/master/docs/rules/no-suite-dupes.md) rule.

**Comment by lxanders** [comment]
@tlvince and @lo1tuma: I like the idea too. Just as a small word of warning: I do not know how we want to share the work though and how fast it can be done but I'm totally for it and @lo1tuma and me will talk about this (we should make this clear here so no work is duplicated).

**Comment by tlvince** [comment]
I haven't a clear vision yet, but will start on something when I have time. NB, we just released [no-spec-dupes](https://github.com/tlvince/eslint-plugin-jasmine/blob/dedc3f002e09c2b9302a3f6a0ea2c7d8742acc63/docs/rules/no-spec-dupes.md), which could be a good candidate.
