### ISSUE TITLE
Remove no-skipped-tests from recommended

### ISSUE THREAD

**Issue by edg2s** [lo1tuma/eslint-plugin-mocha#250]
We had a similar discussion on eslint-plugin-qunit: https://github.com/platinumazure/eslint-plugin-qunit/issues/86#issuecomment-633759027

It's a fine rule, but it seems to be a matter of preference if you want to leave skipped tests in your code as explicit TODOs, in which case they shouldn't be disallowed.

**Comment by lo1tuma** [comment]
The recommended config has this rule only configured to report warnings. If the intent of skipped tests is to act as TODO then it would be good to get reminded about it, which you actually get with warnings.

**Comment by lo1tuma** [comment]
Closing for now. Please let me know if this is still a problem.
