### ISSUE TITLE
no-mocha-arrows drops comments in the function head when fixing

### ISSUE THREAD

**Issue by edg2s** [lo1tuma/eslint-plugin-mocha#251]
All of these comments are dropped when fixing:
```js
it( ( foo /* one */ ) /* two */ => /* three */ { body(); } );
```

This was noticed while porting this rule to eslint-plugin-qunit: https://github.com/platinumazure/eslint-plugin-qunit/pull/88

The fixes there can be easily backported to this plugin.

**Comment by lo1tuma** [comment]
Thanks for reporting. This looks like a bug.
