### ISSUE TITLE
Remove no-hooks-for-single-case from recommended

### ISSUE THREAD

**Issue by edg2s** [lo1tuma/eslint-plugin-mocha#252]
The number of test in a group may fluctuate over the course of development. While there may be only one test this week, there may be three next week, and back to one the week after. As a developer I wouldn't want to have refactor out the setup/teardown into before/after functions each time I go from have one test to many tests or vice-versa.

Structuring your code to be more flexible for future changes in not really an anti-pattern that warrants inclusion in the recommended config.

**Comment by nopeless** [comment]
Agreed I don't have a single idea why this is even a problem

**Comment by rachidlamouri** [comment]
Additionally, if this rule is enabled then what is the recommended way to add teardown to a single test case? If an error is thrown in the test case doesn't it end without running the teardown?
