### ISSUE TITLE
`max-top-level-suites` not warning for test files with multiple describe blocks

### ISSUE THREAD

**Issue by hbergren** [lo1tuma/eslint-plugin-mocha#254]
I have `'mocha/max-top-level-suites': ['error', { limit: 1 }]` as my config, but yet, there are no warnings for test files with multiple describe blocks.

My project is a TypeScript project if that's at all relevant.

I'm happy to help diagnose this, but i'm not sure where to begin.

**Comment by lo1tuma** [comment]
Looks like a duplicate of #248.

**Comment by hbergren** [comment]
Good catch. I'll close in favor of #248.
