### ISSUE TITLE
Support ESLint 8.x

### ISSUE THREAD

**Issue by MichaelDeBoey** [lo1tuma/eslint-plugin-mocha#298]
ESLint v8.0.0 is [released](https://eslint.org/blog/2021/10/eslint-v8.0.0-released) 🎉

It would be awesome to have official ESLint 8 support. 👊
I'm happy to help where I can of course 🙂

**Comment by lo1tuma** [comment]
Has anyone actually tried the current version `9.0.0` of `eslint-plugin-mocha` with `eslint` v8 and is experiencing any issues?

I don’t think a release is needed for a devDepenency update, as it should not affect the installable package artifact.

**Comment by lo1tuma** [comment]
There is a new version `10.0.0` with updated devDependencies, although I’m pretty sure it doesn’t matter what ESLint version we are using in devDependencies.
