### ISSUE TITLE
Rule proposal: no-empty-description

### ISSUE THREAD

**Issue by pustovitDmytro** [lo1tuma/eslint-plugin-mocha#302]
Hi, that's would be awesome to catch empty suites/tests. 

```js
test('', function () {
    assert.equal(2 + 2, 4);
});
```

Of course, I can use `valid-suite-description`/ `valid-test-description` rules to enforce descriptions format, but I don't have a specific convention, and a lightweight `no-empty` rule will be useful for such a case.

I'm ready to provide help with implementation, if needed.

**Comment by lo1tuma** [comment]
I think that is a great idea 👍.
