### ISSUE TITLE
Breaking change accidentally release in 10.4.0

### ISSUE THREAD

**Issue by newhouse** [lo1tuma/eslint-plugin-mocha#351]
Hi there - love this package and thanks for all the hard work!

There is a problem with your latest release of `10.4.0` however:
- `10.4.0` of `eslint-plugin-mocha` added the `"globals": "^14.0.0"` dependency.
- `globals@14.0.0` has a node engines requirement of `>=18`.
- `eslint-plugin-mocha` v`10.4.0` still has an engines requirement of `>=14.0.0` (though it seems like you're moving towards 20 as evidenced by what's in `main`).

This is an accidentally breaking change for projects (like one of ours) that are running on Node 16, with a dependency of something like `"eslint-plugin-mocha": "^10.2.0"`

I'm not sure what you're using from `globals`, but it seems like `13` is compatible with Node `>=8`, so you can probably just change your dependency to some version of 13 and be ok, or perhaps with minor changes.

Would you consider fixing things in a patch of some sort in the `10.x` semver realm?

**Comment by lo1tuma** [comment]
Thanks for reporting. I’ve downgraded `globals` to `13.24.0` and made a patch release of `eslint-plugin-mocha`, so `v10.4.1` should hopefully fix this issue. Please let me know it it works for you.

**Comment by lo1tuma** [comment]
> BTW, this package specifies `engines.node>=20.0.0` in package.json. What are the supported Node.js versions?

The `main` branch contains unreleased breaking changes which I planning to release as part of `eslint-plugin-mocha` v11. But I’ve cherry-picked the changes from #349 to make another 10.x release.

**Comment by newhouse** [comment]
Thanks @lo1tuma and @rhysd !

Things look good now with `^10.14.1`.

I haven't looked closely over the timing of various changes, etc, but was surprised it was not caught in the CI tests given that you had a matrix of all supported engines set up:
https://github.com/lo1tuma/eslint-plugin-mocha/commit/767d90053df13cdbbd23f3d14c52d10148986871

Anyways, thanks again!!! You can close this, IMO.

**Comment by falkenhawk** [comment]
can the `globals` dependency version range be extended from `^13.24.0" to ">=13.24.0" please?
