### ISSUE TITLE
Latest Version 10.4.2. is throwing TypeError: Cannot read properties of undefined (reading 'getScope') 

### ISSUE THREAD

**Issue by Gynormous** [lo1tuma/eslint-plugin-mocha#353]
Just bumped to latest package from 10.4.1 to 10.4.2 and have started receiving the following error:

**_TypeError: Cannot read properties of undefined (reading 'getScope')
Occurred while linting /xxx/some/path/to/test/...
Rule: "XXXXX"_**

Unsure why sourceCode in the patch commit is undefined.

**Comment by Gynormous** [comment]
Issue is due to compatibility issue with eslint 8. You must be on latest version of 8 for it to work without going to V9

**Comment by MikeMcC399** [comment]
@Gynormous 

- This was due to https://github.com/lo1tuma/eslint-plugin-mocha/issues/354 and it's fixed in [10.4.3](https://github.com/lo1tuma/eslint-plugin-mocha/releases/tag/10.4.3)
