### ISSUE TITLE
Rule proposal: forbid top level before / after hooks 

### ISSUE THREAD

**Issue by lo1tuma** [lo1tuma/eslint-plugin-mocha#37]
Those should be only used in a describe block

**Comment by lxanders** [comment]
I like this proposal, this feature is definitely useful IMHO.

**Comment by Badestrand** [comment]
Just asking: Why would you want to forbid this? I for one have some tests where I have global *before* prequisites. To get around that ban I would need to declare a useless describe.. I can't see the benefit

**Comment by lo1tuma** [comment]
Sometimes a before or after hook is accidentally placed outside of a describe block causing strange side effects for other tests. If this happens, it is really hard to find where the hook was defined.

**Comment by benmosher** [comment]
@badestrand: in that case, you could turn the rule off. 

My rule of thumb for what makes a good ESLint rule is: "what is something that is easy to detect with a machine, not obvious to a human, and _generally_ unnecessary."

I agree that global hooks could be very useful, but IME the one time I used them was unintentionally and with bizarre, negative consequences. 😅

**Comment by atakiel** [comment]
Perhaps the rule could warn for root level hooks if the file contains a describe block. This would spot possible unintentional root level hook definitions.

But as root level hooks are useful for many test cases, it would be handy to define root level hooks in a dedicated hooks file.

Part of the functionality could possibly be behind an option. Disallow all by default, and only allow separate file by option.

**Comment by benmosher** [comment]
There is always [eslint-disable](http://eslint.org/docs/user-guide/configuring). 

Serves the dual purpose of disabling the warning and letting humans know you meant to do it. (Again, assuming you generally _want_ the rule enabled)
