### ISSUE TITLE
Rule proposal: avoid before / after hooks

### ISSUE THREAD

**Issue by lo1tuma** [lo1tuma/eslint-plugin-mocha#39]
Using `before` or `after` hooks is almost always a sign that you use shared state between multiple tests. This could lead to unwanted side-effects, e.g. some tests only pass/fail if the tests are executed in a specific order.

**Comment by jfmengels** [comment]
Should this then also forbid `beforeEach` and `afterEach`? I'm thinking to yes as it follows the same shared state problem.

**Comment by lo1tuma** [comment]
You are right, the same problem could be created by `beforeEach` and `afterEach`.
I think if someone needs to distinguish between all and every hooks we can always add an option to the rule later.
