### ISSUE TITLE
Don't autofix no-exclusive-tests

### ISSUE THREAD

**Issue by Moeriki** [lo1tuma/eslint-plugin-mocha#60]
With autofix eslint is becoming a great tool to fix stylistic linting issues in code. I love having `--fix` on save in Atom's `linter-eslint`.

While I love `no-exclusive-tests` to make sure I don't commit `.only` (pre-commit hook). Having autofix removing `.only` on save is obviously undesired.

Right now the only solution for this is disabling the `no-exclusive-tests` rule. It would be great to have autofix be opt-in for this rule.

**Comment by lo1tuma** [comment]
Thanks for the issue and sorry for the late response.

This totally makes sense to me. Personally I’m using eslint’s autofix feature very rarely so I wouldn’t miss it `no-exclusive-tests`.

What do you think @lxanders?

**Comment by lo1tuma** [comment]
If we remove autofix from `no-exclusive-tests` should remove it from `no-skipped-tests` too?

**Comment by wietsevenema** [comment]
I wouldn't mind keeping it for the no-skipped-tests, rarely use that. Updated the PR to make the build green.

**Comment by lxanders** [comment]
Thanks for your pull request @Moeriki! Yeah I think this is a good idea. I'm using auto fixing rarely, too but if I did it would definitely be disturbing if it removed `.only` while developing. About `no-skipped-tests`: I don't think the main usage of `.skip` is to narrow down the tests executed in development mode so the auto-fixing of that might be less disturbing in development.

So to sum up: I'd remove the auto-fixing of `no-exclusive-tests` but not do the same (for now) with `no-skipped-tests`.

**Comment by Moeriki** [comment]
Thanks for your pull request @wietsevenema ;)

Thanks for acceptance. I've committed `.only` once too many last weeks!

**Comment by lxanders** [comment]
Damn, so I was reading too sloppy 😀 . Thanks for the pull request @wietsevenema & thanks for the issue and correcting me @Moeriki 😉 .

**Comment by lo1tuma** [comment]
Thanks everyone.

This change has been released in version 3.0.0.

**Comment by wietsevenema** [comment]
That's great, thanks!
