### ISSUE TITLE
Export a recommended plugin configuration

### ISSUE THREAD

**Issue by alecxe** [lo1tuma/eslint-plugin-mocha#67]
Please export a recommended plugin configuration similar to how other plugins do that:

 * https://github.com/alecxe/eslint-plugin-protractor/blob/master/index.js#L32
 * https://github.com/tlvince/eslint-plugin-jasmine/blob/master/index.js#L16

Additionally, mention it in the documentation ([sample](https://github.com/tlvince/eslint-plugin-jasmine#configuration)).

Thank you!

**Comment by lo1tuma** [comment]
Thanks for the request.

I think first we would need to discuss about what rules we should recommend.
Currently I would probably only include `no-exclusive-tests`.

cc: @lxanders

**Comment by alecxe** [comment]
Btw, just to save time, here is a [test](https://github.com/alecxe/eslint-plugin-protractor/blob/master/test/index.js#L31-L37) I've added to my plugin to check that plugin ships with a recommended error level for every defined rule.

**Comment by lo1tuma** [comment]
Why should the recommended config include all rules?

**Comment by alecxe** [comment]
@lo1tuma right, it is definitely not mandatory to include recommended configs for all the rules. I am just following the "Explicit is better than implicit" philosophy preferring to explicitly state that the rule is "off" than implicitly not including it into the config. Thanks.
