### ISSUE TITLE
Switch to semantic releasing

### ISSUE THREAD

**Issue by alecxe** [lo1tuma/eslint-plugin-mocha#77]
Consider switching to [`semantic-release`](https://github.com/semantic-release/semantic-release) package publishing and a more strict commit message format.

This proved to work quite well and transparently for me at https://github.com/alecxe/eslint-plugin-protractor. 

Thanks.

**Comment by lo1tuma** [comment]
Thanks for request.

Actually I don’t like the commit-message based changelog generation. I prefer do to [baby-steps](https://talboomerik.be/2012/01/16/taking-baby-steps/) and I’m following the red/green/refactor cycle approach where each cycle ends with a commit. Sometimes I even try to come up with pre-emptive commit messages.
This is also the reason why I implemented [`pr-log`](https://github.com/lo1tuma/pr-log) which generates to changelog from pull request titles and doesn’t care about commit messages.

**Comment by alecxe** [comment]
@lo1tuma yeah, it is a matter of a personal preference. Just wanted to check with you if you like the idea.  I'll look into `pr-log` closely, nice idea! Thanks!

Omg, I see that emberassing merge commit I've done. We should probably get rid of it :)
