### ISSUE TITLE
Why `no-synchronous-tests` running inside of `before` and `after`?

### ISSUE THREAD

**Issue by amilajack** [lo1tuma/eslint-plugin-mocha#96]
Why is running `done` inside of `after` necessary? I dont think it is.

**Comment by lo1tuma** [comment]
Hooks can also [be asynchronous](http://mochajs.org/#asynchronous-hooks). That’s why I think the same rules as for tests should apply for them.

**Comment by sloncho** [comment]
It'll be beneficial if we can configure the error level by type - hook or test. I.e. for hooks, it should be a warning, but for tests it's much better if it's an error.
